# Generated by Django 4.1.5 on 2023-02-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_dish_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
