# Generated by Django 4.1.5 on 2023-02-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_cook_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dish_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
