# Generated by Django 4.1.5 on 2023-02-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_dish_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishtype',
            name='dish_type_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
